config/routes.rb
Rails.application.routes.draw do
  
  root 'apartments#index'
  
  resources :apartments do
    get 'map_location'
  end
  
  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
 #devise associations
  belongs_to :user

  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def full_address
    @address = address
    @street = street
    @city = city
    @postal_code = postal_code
    @state = state
    @country = country
    @full_address = (@address+" "+@street+" "+@city+ " "+@postal_code+" "+@state+" "+@country)
  end


  geocoded_by :full_address
  after_validation :geocode


end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
#Setting up our page so that non signed in users cannot edit or destroy apartment listings
  before_action :authenticate_user!, except: [:index, :show]

  # GET /apartments
  # GET /apartments.json
  #spent over 4hrs before figuring out my full map wasnt showing cos i didnt change @hash to @pindrop and @apartment to @apartments
  def index
    @apartments = Apartment.all
    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
  end

  def show
    @apartments = Apartment.find(params[:id])
      @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
        marker.lat apartment.latitude
        marker.lng apartment.longitude
        marker.infowindow apartment.full_address
      end
  end

def map_location
  @apartment = Apartment.find(params[:apartment_id])
  @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
    marker.lat apartment.latitude
    marker.lng apartment.longitude
    marker.infowindow apartment.full_address
  end
end
render json: @hash.to_json

  # GET /apartments/new
  def new
    @apartment = current_user.apartments.build
  end

  # GET /apartments/1/edit
  def edit
  end


  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_user.apartments.build(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:latitude, :longitude, :address, :street, :city, :postal_code, :state, :country, :landlord_name, :contact_number, :hours, :image, :username, :login)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for @apartment, html: { multipart: true } do |f| %> <!--change this for paperclip-->
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<form class="form-horizontal">
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %><br>
    <div class="col-sm-10">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class = "form-group">
      <%= f.label :latitude, class: "col-sm-2 control-label" %><br>
      <div class="col-sm-10">
      <%= f.text_field :latitude %>
    </div>
  </div>

  <div class = "form-group">
  <%= f.label :longitude, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :longitude %>
  </div>
</div>

<div class = "form-group">
<%= f.label :address, class: "col-sm-2 control-label" %><br>
<div class="col-sm-10">
  <%= f.text_field :address %>
</div>
</div>


<div class = "form-group">
  <%= f.label :street, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :street %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :city, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :city %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :postal_code, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :postal_code %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :state, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :state %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :country, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :country %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :landlord_name, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :landlord_name %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :contact_number, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :contact_number %>
  </div>
</div>

<div class = "form-group">
  <%= f.label :hours, class: "col-sm-2 control-label" %><br>
  <div class="col-sm-10">
    <%= f.text_field :hours %>
  </div>
</div><br>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-warning" %>
</div>
</div>
</form>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>



<table class="table">
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Street</th>
      <th>City</th>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th>Landlord name</th>
      <th>Contact number</th>
      <th>Hours</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.latitude %></td>
        <td><%= apartment.longitude %></td>
        <td><%= apartment.address %></td>
        <td><%= apartment.street %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.postal_code %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.landlord_name %></td>
        <td><%= apartment.contact_number %></td>
        <td><%= apartment.hours %></td>
        <td><%= apartment.user.username %></td>
        <td><%= image_tag apartment.image.url(:thumb) %></td> <!--Adds thumbnail images to list screen-->
        <td><%= link_to 'Show', apartment %></td>
        <!--Prevents anyone who is not signed in from seeing the edit and destroy button-->
        <!--restricts access so that only the user who created an apartment casn delete or edit it-->
        <% if apartment.user == current_user %>
          <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
          <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

<hr/>
<div id="map_all">Google map will appear here...</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {styles: [
      {
        "weight": 1.5
      },
  {
    "featureType": "landscape.man_made",
    "stylers": [
      {
        "visibility": "on"
      }
    ]
  },
  {
    "featureType": "landscape.natural",
    "stylers": [
      {
        "visibility": "on"
      }
    ]
  },
  {
    "featureType": "poi",
    "stylers": [
      {
        "visibility": "on"
      }
    ]
  }
]}, //added google maps custom styling to show terrain
  internal: {id: 'map_all'}},
  function(){
  markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @apartment.image.url(:medium) %>  <!--Add this to display your image after upload-->

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @apartment.address %>
</p>

<p>
  <strong>Street:</strong>
  <%= @apartment.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @apartment.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Landlord name:</strong>
  <%= @apartment.landlord_name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @apartment.contact_number %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @apartment.hours %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

<hr/>

<!--DIV CONTAINING MAP DISPLAY--> <!--MAP SCRIPT to create your map:-->
<div class="col-md-6" id="map" data-apartment-id="<%=@apartment.id%>">Google map will appear here...</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {},
  internal: {id: 'map'}},
  function(){
  markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>